version: '3'

services:

  mongo:
    image: mongo
    environment:
      - MONGO_INITDB_DATABASE=strapi
    ports:
      - 27017:27017

  postgres:
    image: postgres
    environment: 
      - POSTGRES_DB=strapi
    ports:
      - 5432:5432
